# Generated by Django 4.2.7 on 2024-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
